site_name: Pardot API Documentation

site_url: http://developer.pardot.com
site_description: Official documentation for the Pardot API

repo_url: https://github.com/Pardot/api-docs

theme:
    name: null
    custom_dir: 'pardot_theme'

nav:
    - Overview: 'index.md'
    - API:
        - 'Authentication': 'kb/authentication.md'
        - 'Release Notes': 'kb/release-notes.md'
        - 'Version 4': 'kb/api-version-4.md'
        - 'Object Field References': 'kb/object-field-references.md'
        - 'Error Codes & Messages': 'kb/error-codes-messages.md'
        - 'Bulk Data Pull': 'kb/bulk-data-pull.md'
    - '**HIDDEN**':
        - 'Object Field References (Version 3)': 'kb/api-version-3/object-field-references.md'
        - 'Object Field References (Version 4)': 'kb/api-version-4/object-field-references.md'
        - 'Error Codes & Messages': 'kb/api-version-3/error-codes-messages.md'
    - 'Version 3':
        - 'Accounts': 'kb/api-version-3/accounts.md'
        - 'Campaigns': 'kb/api-version-3/campaigns.md'
        - 'Custom Fields': 'kb/api-version-3/custom-fields.md'
        - 'Custom Redirects': 'kb/api-version-3/custom-redirects.md'
        - 'Dynamic Content': 'kb/api-version-3/dynamic-content.md'
        - 'Email': 'kb/api-version-3/emails.md'
        - 'Email Clicks': 'kb/api-version-3/batch-email-clicks.md'
        - 'Email Templates': 'kb/api-version-3/email-templates.md'
        - 'Forms': 'kb/api-version-3/forms.md'
        - 'Lifecycle Histories': 'kb/api-version-3/lifecycle-histories.md'
        - 'Lifecycle Stages': 'kb/api-version-3/lifecycle-stages.md'
        - 'Lists': 'kb/api-version-3/lists.md'
        - 'List Memberships': 'kb/api-version-3/list-memberships.md'
        - 'Opportunities': 'kb/api-version-3/opportunities.md'
        - 'Prospects': 'kb/api-version-3/prospects.md'
        - 'Prospect Accounts': 'kb/api-version-3/prospect-accounts.md'
        - 'Tags': 'kb/api-version-3/tags.md'
        - 'TagObjects': 'kb/api-version-3/tag-objects.md'
        - 'Users': 'kb/api-version-3/users.md'
        - 'Visitors': 'kb/api-version-3/visitors.md'
        - 'Visitor Activities': 'kb/api-version-3/visitor-activities.md'
        - 'Visits': 'kb/api-version-3/visits.md'
        - '--Import API (for Prospects)': 'kb/api-version-3/import.md'
        - 'Export API (for Visitor Activity)': 'kb/api-version-3/export.md'
    - 'Version 4':
        - 'Accounts': 'kb/api-version-4/accounts.md'
        - 'Campaigns': 'kb/api-version-4/campaigns.md'
        - 'Custom Fields': 'kb/api-version-4/custom-fields.md'
        - 'Custom Redirects': 'kb/api-version-4/custom-redirects.md'
        - 'Dynamic Content': 'kb/api-version-4/dynamic-content.md'
        - 'Email': 'kb/api-version-4/emails.md'
        - 'Email Clicks': 'kb/api-version-4/batch-email-clicks.md'
        - 'Email Templates': 'kb/api-version-4/email-templates.md'
        - 'Forms': 'kb/api-version-4/forms.md'
        - 'Lifecycle Histories': 'kb/api-version-4/lifecycle-histories.md'
        - 'Lifecycle Stages': 'kb/api-version-4/lifecycle-stages.md'
        - 'Lists': 'kb/api-version-4/lists.md'
        - 'List Memberships': 'kb/api-version-4/list-memberships.md'
        - 'Opportunities': 'kb/api-version-4/opportunities.md'
        - 'Prospects': 'kb/api-version-4/prospects.md'
        - 'Prospect Accounts': 'kb/api-version-4/prospect-accounts.md'
        - 'Tags': 'kb/api-version-4/tags.md'
        - 'TagObjects': 'kb/api-version-4/tag-objects.md'
        - 'Users': 'kb/api-version-4/users.md'
        - 'Visitors': 'kb/api-version-4/visitors.md'
        - 'Visitor Activities': 'kb/api-version-4/visitor-activities.md'
        - 'Visits': 'kb/api-version-4/visits.md'
        - '--Import API (for Prospects)': 'kb/api-version-4/import.md'
        - 'Export API (for Visitor Activity)': 'kb/api-version-4/export.md'
